name: deploy

on:
  schedule:
    - cron: "0 19 * * *"

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd Omok-BE
            git reset --hard
            git fetch
            git pull
            sudo pm2 restart all